name: lambda-build-push-deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ECR_REPOSITORY: image-processor/lamda
  LAMBDA_FUNCTION: image-processor

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::931814980669:role/GitHubActions-Deployment-Rolee
          aws-region: eu-north-1

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          provenance: false
          sbom: false
          push: true
          tags: |
            ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION }} \
            --image-uri ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Wait for update to finish
        run: |
          aws lambda wait function-updated \
            --function-name ${{ env.LAMBDA_FUNCTION }}

      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ env.LAMBDA_FUNCTION }} \
            --environment "Variables={NOTIFY_MODE=api,BACKEND_URL=http://image-alb-234781079.eu-north-1.elb.amazonaws.com,LAMBDA_API_KEY=${{ secrets.LAMBDA_API_KEY }},MAX_WIDTH=2000,JPEG_QUALITY=80}"